# Use Java 21
FROM eclipse-temurin:21-jdk-alpine

# Copy project files
WORKDIR /app
COPY . .

# Build the project
RUN ./mvnw clean package -DskipTests

# Run the jar file
CMD ["java", "-jar", "target/*.jar"]